export const tableEmptyUz = {
  generic: "Ma'lumot yo'q",
  manager: "Menejer biriktirilmagan",
  calendarDay: "Kun belgilanmagan",
  contractId: "Shartnoma ID yo'q",
  contractDate: "Sana belgilanmagan",
  nextPaymentDate: "Keyingi to'lov sanasi yo'q",
  customer: "Mijoz ma'lumoti yo'q",
  nameUnknown: "Noma'lum",
  paymentProgress: "Muddat aniqlanmagan",
  extras: "Qo‘shimcha yo'q",
  notes: "Izoh yo'q",
  status: "Holat aniqlanmagan",
  paymentMethod: "To'lov usuli ko'rsatilmagan",
  reminderNoPayment: "To'lov emas (eslatma)",
  nextPaymentClear: "Qoldiq yo'q",
  delayNone: "Kechikish yo'q",
  role: "Rol biriktirilmagan",
  phone: "Telefon yo'q",
  customerName: "Mijoz nomi yo'q",
  fileMissing: "Fayl yuklanmagan",
  address: "Manzil kiritilmagan",
  passportSeries: "Passport ma'lumoti yo'q",
  birthDate: "Tug'ilgan sana yo'q",
  targetMonth: "Oy belgilanmagan",
} as const;
